version: "3"
services:
    app:
        build: .
        ports: 
            - 9000:9000
        depends_on: 
            - db 
        restart: on-failure 
        environment: 
            - DATABASE_HOST=db 
        volumes: 
            - ./app

    db:
        image: mysql:5.7 
        ports: 
            - 3306:3306 
        environment:  
            - MYSQL_ROOT_PASSWORD=@root
            - MYSQL_DATABASE=gopher
            - MYSQL_USER=von
            - MYSQL_PASSWORD=@vonmutinda
            - DATABASE_HOST=127.0.0.1
 
